rootProject.name = "Gamedge"

include(":app")
include(":domain")
include(":data")
include(":database")
include(":igdb-api")
include(":igdb-apicalypse")
include(":commons-data")
include(":core")
include(":commons-ui")
include(":commons-ui-widgets")
include(":image-loading")
include(":gamespot-api")
include(":commons-api")
include(":feature-category")
include(":feature-dashboard")
include(":feature-discovery")
include(":feature-info")
include(":feature-image-viewer")
include(":feature-likes")
include(":feature-news")
include(":feature-search")
include(":feature-splash")