// Generated by @BindType. Do not modify!

import dagger.Binds;
import dagger.Module;
import dagger.hilt.InstallIn;
import dagger.hilt.components.SingletonComponent;
import dagger.multibindings.IntoSet;

@Module
@InstallIn(SingletonComponent.class)
public interface HiltBinder_SingletonComponentModule {
    @Binds
    @IntoSet
    Testable bind_Test1(Test1 binding);

    @Binds
    @IntoSet
    Testable bind_Test2(Test2 binding);

    @Binds
    @IntoSet
    Testable bind_Test3(Test3 binding);
}