// Generated by @BindType. Do not modify!
package com.paulrybitskyi.hiltbinder.test;

import dagger.Binds;
import dagger.Module;
import dagger.hilt.InstallIn;
import dagger.hilt.components.SingletonComponent;
import javax.inject.Named;

@Module
@InstallIn(SingletonComponent.class)
public interface HiltBinder_SingletonComponentModule {
    @Binds
    @Named("test")
    Testable bind_com_paulrybitskyi_hiltbinder_test_Test(Test binding);
}