// Generated by @BindType. Do not modify!

import dagger.Binds;
import dagger.Module;
import dagger.hilt.InstallIn;
import dagger.hilt.components.SingletonComponent;
import dagger.multibindings.IntoMap;

@Module
@InstallIn(SingletonComponent.class)
public interface HiltBinder_SingletonComponentModule {
    @Binds
    @IntoMap
    @TestMapKey(TestMapKey.Type.ONE)
    Testable bind_Test1(Test1 binding);

    @Binds
    @IntoMap
    @TestMapKey(TestMapKey.Type.TWO)
    Testable bind_Test2(Test2 binding);

    @Binds
    @IntoMap
    @TestMapKey(TestMapKey.Type.THREE)
    Testable bind_Test3(Test3 binding);
}