// Generated by @BindType. Do not modify!
package com.paulrybitskyi.hiltbinder.testing;

import com.paulrybitskyi.hiltbinder.testing.feature1.interfaces.testing.Test1;
import com.paulrybitskyi.hiltbinder.testing.feature1.interfaces.testing.Testable1;
import com.paulrybitskyi.hiltbinder.testing.feature2.repositories.model.Test2;
import com.paulrybitskyi.hiltbinder.testing.feature2.repositories.model.Testable2;
import com.paulrybitskyi.hiltbinder.testing.utils.interfaces.Test3;
import com.paulrybitskyi.hiltbinder.testing.utils.interfaces.Testable3;

import dagger.Binds;
import dagger.Module;
import dagger.hilt.InstallIn;
import dagger.hilt.components.SingletonComponent;

@Module
@InstallIn(SingletonComponent.class)
public interface HiltBinder_SingletonComponentModule {
    @Binds
    Testable1 bind_com_paulrybitskyi_hiltbinder_testing_feature1_interfaces_testing_Test1(Test1 binding);

    @Binds
    Testable2 bind_com_paulrybitskyi_hiltbinder_testing_feature2_repositories_model_Test2(Test2 binding);

    @Binds
    Testable3 bind_com_paulrybitskyi_hiltbinder_testing_utils_interfaces_Test3(Test3 binding);
}