// Generated by @BindType. Do not modify!

import dagger.Binds;
import dagger.Module;
import dagger.hilt.InstallIn;
import dagger.hilt.components.SingletonComponent;
import dagger.multibindings.ClassKey;
import dagger.multibindings.IntoMap;
import javax.inject.Named;

@Module
@InstallIn(SingletonComponent.class)
public interface HiltBinder_SingletonComponentModule {
    @Binds
    @IntoMap
    @ClassKey(Test1.class)
    @Named("one")
    Testable bind_Test1(Test1 binding);

    @Binds
    @IntoMap
    @ClassKey(Test2.class)
    @Named("two")
    Testable bind_Test2(Test2 binding);

    @Binds
    @IntoMap
    @ClassKey(Test3.class)
    @Named("three")
    Testable bind_Test3(Test3 binding);
}