// Generated by @BindType. Do not modify!

import dagger.Binds;
import dagger.Module;
import dagger.hilt.InstallIn;
import dagger.hilt.components.SingletonComponent;
import dagger.multibindings.IntoMap;
import dagger.multibindings.StringKey;

@Module
@InstallIn(SingletonComponent.class)
public interface HiltBinder_SingletonComponentModule {
    @Binds
    @IntoMap
    @StringKey("one")
    Testable bind_Test1(Test1 binding);

    @Binds
    @IntoMap
    @StringKey("two")
    Testable bind_Test2(Test2 binding);

    @Binds
    @IntoMap
    @StringKey("three")
    Testable bind_Test3(Test3 binding);
}